export const revalidate = 0;
import { supabase } from '@/lib/supabaseClient';
import FlashcardList from '@/components/FlashcardList';
import PracticeInterface from '@/components/PracticeInterface';

export default async function PracticePage() {
  // Fetch flashcards (existing functionality)
  const { data: flashcards } = await supabase
    .from('flashcards')
    .select('*')
    .order('created_at', { ascending: false });

  // Fetch resources for quiz generation
  const { data: resources } = await supabase
    .from('resources')
    .select('*')
    .not('content', 'is', null)
    .order('created_at', { ascending: false });

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-900 via-purple-800 to-indigo-900">
      <div className="container mx-auto px-4 py-8">
        <div className="max-w-6xl mx-auto space-y-8">
          <div className="text-center">
            <h1 className="text-4xl font-bold text-white mb-4">
              Practice Platform
            </h1>
            <p className="text-lg text-purple-200">
              Review flashcards and take quizzes generated by the AetherOS AI
            </p>
          </div>
          
          <PracticeInterface 
            flashcards={flashcards || []} 
            resources={resources || []} 
          />
        </div>
      </div>
    </div>
  );
}