// in app/practice/page.tsx
export const revalidate = 0;
import { supabase } from '@/lib/supabaseClient';
import FlashcardList from '@/components/FlashcardList';

export default async function PracticePage() {
  const { data: flashcards } = await supabase.from('flashcards').select('*').order('created_at', { ascending: false });

  return (
    <div className="space-y-8">
      <h1 className="text-3xl font-bold text-white">Practice Platform</h1>
      <p className="text-neutral-400">Review the flashcards generated by the AetherOS AI.</p>
      <FlashcardList flashcards={flashcards || []} />
    </div>
  );
}